// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/event.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_CreateEvent_FullMethodName          = "/event.EventService/CreateEvent"
	EventService_ListUserEvents_FullMethodName       = "/event.EventService/ListUserEvents"
	EventService_ListEvents_FullMethodName           = "/event.EventService/ListEvents"
	EventService_GetEvent_FullMethodName             = "/event.EventService/GetEvent"
	EventService_UpdateEvent_FullMethodName          = "/event.EventService/UpdateEvent"
	EventService_JoinEvent_FullMethodName            = "/event.EventService/JoinEvent"
	EventService_LeaveEvent_FullMethodName           = "/event.EventService/LeaveEvent"
	EventService_RemoveParticipant_FullMethodName    = "/event.EventService/RemoveParticipant"
	EventService_GetEventParticipants_FullMethodName = "/event.EventService/GetEventParticipants"
	EventService_AddChecklistItem_FullMethodName     = "/event.EventService/AddChecklistItem"
	EventService_RemoveChecklistItem_FullMethodName  = "/event.EventService/RemoveChecklistItem"
	EventService_MarkItemPurchased_FullMethodName    = "/event.EventService/MarkItemPurchased"
	EventService_GetEventChecklist_FullMethodName    = "/event.EventService/GetEventChecklist"
	EventService_CancelEvent_FullMethodName          = "/event.EventService/CancelEvent"
	EventService_CreateInviteLink_FullMethodName     = "/event.EventService/CreateInviteLink"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис управления мероприятиями (Eventify)
type EventServiceClient interface {
	// Создать новое мероприятие
	// Требует авторизации
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	// Получить список мероприятий конкретного пользователя
	// Требует авторизации
	ListUserEvents(ctx context.Context, in *ListUserEventsRequest, opts ...grpc.CallOption) (*ListUserEventsResponse, error)
	// Получить список всех мероприятий
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	// Получить информацию о конкретном мероприятии по его ID
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error)
	// Обновить информацию о конкретном мероприятии по его ID
	// Требует авторизации
	UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateEventResponse, error)
	// Присоединиться к мероприятию по ссылке.
	// Требует авторизации
	JoinEvent(ctx context.Context, in *JoinEventRequest, opts ...grpc.CallOption) (*JoinEventResponse, error)
	// Выход пользователя из мероприятия
	// Требует авторизации
	LeaveEvent(ctx context.Context, in *LeaveEventRequest, opts ...grpc.CallOption) (*LeaveEventResponse, error)
	// Удалить участника из мероприятия
	// Требует авторизации и проверки роли
	RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*RemoveParticipantResponse, error)
	// Получить список участников
	GetEventParticipants(ctx context.Context, in *GetEventParticipantsRequest, opts ...grpc.CallOption) (*GetEventParticipantsResponse, error)
	// Добавить предмет в чеклист
	// Требует авторизации
	AddChecklistItem(ctx context.Context, in *AddChecklistItemRequest, opts ...grpc.CallOption) (*AddChecklistItemResponse, error)
	// Удалить предмет из чеклиста
	// Требует Авторизации
	RemoveChecklistItem(ctx context.Context, in *RemoveChecklistItemRequest, opts ...grpc.CallOption) (*RemoveChecklistItemResponse, error)
	// Пометить предмет, как купленный
	// Требует авторизации
	MarkItemPurchased(ctx context.Context, in *MarkItemPurchasedRequest, opts ...grpc.CallOption) (*MarkItemPurchasedResponse, error)
	// Получить чеклист мероприятия
	// Требует авторизации
	GetEventChecklist(ctx context.Context, in *GetEventChecklistRequest, opts ...grpc.CallOption) (*GetEventChecklistResponse, error)
	// Отменить мероприятие
	// Требует авторизации
	CancelEvent(ctx context.Context, in *CancelEventRequest, opts ...grpc.CallOption) (*CancelEventResponse, error)
	// Создание ссылки приглашения на мероприятие со статусом
	// Требует авторизации
	CreateInviteLink(ctx context.Context, in *CreateInviteLinkRequest, opts ...grpc.CallOption) (*CreateInviteLinkResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, EventService_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ListUserEvents(ctx context.Context, in *ListUserEventsRequest, opts ...grpc.CallOption) (*ListUserEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserEventsResponse)
	err := c.cc.Invoke(ctx, EventService_ListUserEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, EventService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventResponse)
	err := c.cc.Invoke(ctx, EventService_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEventResponse)
	err := c.cc.Invoke(ctx, EventService_UpdateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) JoinEvent(ctx context.Context, in *JoinEventRequest, opts ...grpc.CallOption) (*JoinEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinEventResponse)
	err := c.cc.Invoke(ctx, EventService_JoinEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) LeaveEvent(ctx context.Context, in *LeaveEventRequest, opts ...grpc.CallOption) (*LeaveEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveEventResponse)
	err := c.cc.Invoke(ctx, EventService_LeaveEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*RemoveParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveParticipantResponse)
	err := c.cc.Invoke(ctx, EventService_RemoveParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventParticipants(ctx context.Context, in *GetEventParticipantsRequest, opts ...grpc.CallOption) (*GetEventParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventParticipantsResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) AddChecklistItem(ctx context.Context, in *AddChecklistItemRequest, opts ...grpc.CallOption) (*AddChecklistItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddChecklistItemResponse)
	err := c.cc.Invoke(ctx, EventService_AddChecklistItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) RemoveChecklistItem(ctx context.Context, in *RemoveChecklistItemRequest, opts ...grpc.CallOption) (*RemoveChecklistItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveChecklistItemResponse)
	err := c.cc.Invoke(ctx, EventService_RemoveChecklistItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) MarkItemPurchased(ctx context.Context, in *MarkItemPurchasedRequest, opts ...grpc.CallOption) (*MarkItemPurchasedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkItemPurchasedResponse)
	err := c.cc.Invoke(ctx, EventService_MarkItemPurchased_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventChecklist(ctx context.Context, in *GetEventChecklistRequest, opts ...grpc.CallOption) (*GetEventChecklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventChecklistResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventChecklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) CancelEvent(ctx context.Context, in *CancelEventRequest, opts ...grpc.CallOption) (*CancelEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelEventResponse)
	err := c.cc.Invoke(ctx, EventService_CancelEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) CreateInviteLink(ctx context.Context, in *CreateInviteLinkRequest, opts ...grpc.CallOption) (*CreateInviteLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInviteLinkResponse)
	err := c.cc.Invoke(ctx, EventService_CreateInviteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
//
// Сервис управления мероприятиями (Eventify)
type EventServiceServer interface {
	// Создать новое мероприятие
	// Требует авторизации
	CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	// Получить список мероприятий конкретного пользователя
	// Требует авторизации
	ListUserEvents(context.Context, *ListUserEventsRequest) (*ListUserEventsResponse, error)
	// Получить список всех мероприятий
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	// Получить информацию о конкретном мероприятии по его ID
	GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error)
	// Обновить информацию о конкретном мероприятии по его ID
	// Требует авторизации
	UpdateEvent(context.Context, *UpdateEventRequest) (*UpdateEventResponse, error)
	// Присоединиться к мероприятию по ссылке.
	// Требует авторизации
	JoinEvent(context.Context, *JoinEventRequest) (*JoinEventResponse, error)
	// Выход пользователя из мероприятия
	// Требует авторизации
	LeaveEvent(context.Context, *LeaveEventRequest) (*LeaveEventResponse, error)
	// Удалить участника из мероприятия
	// Требует авторизации и проверки роли
	RemoveParticipant(context.Context, *RemoveParticipantRequest) (*RemoveParticipantResponse, error)
	// Получить список участников
	GetEventParticipants(context.Context, *GetEventParticipantsRequest) (*GetEventParticipantsResponse, error)
	// Добавить предмет в чеклист
	// Требует авторизации
	AddChecklistItem(context.Context, *AddChecklistItemRequest) (*AddChecklistItemResponse, error)
	// Удалить предмет из чеклиста
	// Требует Авторизации
	RemoveChecklistItem(context.Context, *RemoveChecklistItemRequest) (*RemoveChecklistItemResponse, error)
	// Пометить предмет, как купленный
	// Требует авторизации
	MarkItemPurchased(context.Context, *MarkItemPurchasedRequest) (*MarkItemPurchasedResponse, error)
	// Получить чеклист мероприятия
	// Требует авторизации
	GetEventChecklist(context.Context, *GetEventChecklistRequest) (*GetEventChecklistResponse, error)
	// Отменить мероприятие
	// Требует авторизации
	CancelEvent(context.Context, *CancelEventRequest) (*CancelEventResponse, error)
	// Создание ссылки приглашения на мероприятие со статусом
	// Требует авторизации
	CreateInviteLink(context.Context, *CreateInviteLinkRequest) (*CreateInviteLinkResponse, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventServiceServer) ListUserEvents(context.Context, *ListUserEventsRequest) (*ListUserEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserEvents not implemented")
}
func (UnimplementedEventServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedEventServiceServer) GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedEventServiceServer) UpdateEvent(context.Context, *UpdateEventRequest) (*UpdateEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (UnimplementedEventServiceServer) JoinEvent(context.Context, *JoinEventRequest) (*JoinEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinEvent not implemented")
}
func (UnimplementedEventServiceServer) LeaveEvent(context.Context, *LeaveEventRequest) (*LeaveEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveEvent not implemented")
}
func (UnimplementedEventServiceServer) RemoveParticipant(context.Context, *RemoveParticipantRequest) (*RemoveParticipantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveParticipant not implemented")
}
func (UnimplementedEventServiceServer) GetEventParticipants(context.Context, *GetEventParticipantsRequest) (*GetEventParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventParticipants not implemented")
}
func (UnimplementedEventServiceServer) AddChecklistItem(context.Context, *AddChecklistItemRequest) (*AddChecklistItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddChecklistItem not implemented")
}
func (UnimplementedEventServiceServer) RemoveChecklistItem(context.Context, *RemoveChecklistItemRequest) (*RemoveChecklistItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveChecklistItem not implemented")
}
func (UnimplementedEventServiceServer) MarkItemPurchased(context.Context, *MarkItemPurchasedRequest) (*MarkItemPurchasedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkItemPurchased not implemented")
}
func (UnimplementedEventServiceServer) GetEventChecklist(context.Context, *GetEventChecklistRequest) (*GetEventChecklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventChecklist not implemented")
}
func (UnimplementedEventServiceServer) CancelEvent(context.Context, *CancelEventRequest) (*CancelEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelEvent not implemented")
}
func (UnimplementedEventServiceServer) CreateInviteLink(context.Context, *CreateInviteLinkRequest) (*CreateInviteLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInviteLink not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call panics, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ListUserEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ListUserEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ListUserEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ListUserEvents(ctx, req.(*ListUserEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateEvent(ctx, req.(*UpdateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_JoinEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).JoinEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_JoinEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).JoinEvent(ctx, req.(*JoinEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_LeaveEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).LeaveEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_LeaveEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).LeaveEvent(ctx, req.(*LeaveEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_RemoveParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).RemoveParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_RemoveParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).RemoveParticipant(ctx, req.(*RemoveParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventParticipants(ctx, req.(*GetEventParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_AddChecklistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddChecklistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddChecklistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_AddChecklistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddChecklistItem(ctx, req.(*AddChecklistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_RemoveChecklistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveChecklistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).RemoveChecklistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_RemoveChecklistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).RemoveChecklistItem(ctx, req.(*RemoveChecklistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_MarkItemPurchased_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkItemPurchasedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).MarkItemPurchased(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_MarkItemPurchased_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).MarkItemPurchased(ctx, req.(*MarkItemPurchasedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventChecklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventChecklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventChecklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventChecklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventChecklist(ctx, req.(*GetEventChecklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_CancelEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CancelEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CancelEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CancelEvent(ctx, req.(*CancelEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_CreateInviteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInviteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateInviteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateInviteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateInviteLink(ctx, req.(*CreateInviteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventService_CreateEvent_Handler,
		},
		{
			MethodName: "ListUserEvents",
			Handler:    _EventService_ListUserEvents_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _EventService_ListEvents_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _EventService_GetEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _EventService_UpdateEvent_Handler,
		},
		{
			MethodName: "JoinEvent",
			Handler:    _EventService_JoinEvent_Handler,
		},
		{
			MethodName: "LeaveEvent",
			Handler:    _EventService_LeaveEvent_Handler,
		},
		{
			MethodName: "RemoveParticipant",
			Handler:    _EventService_RemoveParticipant_Handler,
		},
		{
			MethodName: "GetEventParticipants",
			Handler:    _EventService_GetEventParticipants_Handler,
		},
		{
			MethodName: "AddChecklistItem",
			Handler:    _EventService_AddChecklistItem_Handler,
		},
		{
			MethodName: "RemoveChecklistItem",
			Handler:    _EventService_RemoveChecklistItem_Handler,
		},
		{
			MethodName: "MarkItemPurchased",
			Handler:    _EventService_MarkItemPurchased_Handler,
		},
		{
			MethodName: "GetEventChecklist",
			Handler:    _EventService_GetEventChecklist_Handler,
		},
		{
			MethodName: "CancelEvent",
			Handler:    _EventService_CancelEvent_Handler,
		},
		{
			MethodName: "CreateInviteLink",
			Handler:    _EventService_CreateInviteLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/event.proto",
}
