// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/event.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Информация о мероприятии
type EventInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Название мероприятия
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Описание мероприятия
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Дата-время начала мероприятия
	StartsAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	// Длительность мероприятия
	Duration int32 `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	// Статус мероприятия (draft / active / cancelled / completed)
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// Приватность
	IsPrivate     bool `protobuf:"varint,7,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventInfo) Reset() {
	*x = EventInfo{}
	mi := &file_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInfo) ProtoMessage() {}

func (x *EventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInfo.ProtoReflect.Descriptor instead.
func (*EventInfo) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventInfo) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *EventInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *EventInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventInfo) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

// Информация об участнике мероприятия
// upd: убрали поле name
type ParticipantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId string                 `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	// Роль в мероприятии
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// Участие в мероприятии ('invited', 'confirmed', 'declined', 'maybe')
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantInfo) Reset() {
	*x = ParticipantInfo{}
	mi := &file_proto_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantInfo) ProtoMessage() {}

func (x *ParticipantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantInfo.ProtoReflect.Descriptor instead.
func (*ParticipantInfo) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{1}
}

func (x *ParticipantInfo) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *ParticipantInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ParticipantInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Информация о предмете в чеклисте
type ChecklistItemInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Название товара
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Количество товара
	Quantity int32 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Единица измерения
	Unit string `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	// Опционально: id ответственного
	BuyerId *string `protobuf:"bytes,5,opt,name=buyer_id,json=buyerId,proto3,oneof" json:"buyer_id,omitempty"`
	// Опционально: статус: куплено/нет
	IsPurchased   *bool `protobuf:"varint,6,opt,name=is_purchased,json=isPurchased,proto3,oneof" json:"is_purchased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecklistItemInfo) Reset() {
	*x = ChecklistItemInfo{}
	mi := &file_proto_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecklistItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecklistItemInfo) ProtoMessage() {}

func (x *ChecklistItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecklistItemInfo.ProtoReflect.Descriptor instead.
func (*ChecklistItemInfo) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{2}
}

func (x *ChecklistItemInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChecklistItemInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChecklistItemInfo) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ChecklistItemInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ChecklistItemInfo) GetBuyerId() string {
	if x != nil && x.BuyerId != nil {
		return *x.BuyerId
	}
	return ""
}

func (x *ChecklistItemInfo) GetIsPurchased() bool {
	if x != nil && x.IsPurchased != nil {
		return *x.IsPurchased
	}
	return false
}

// Запрос о создании мероприятия
type CreateEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Название мероприятия
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Описание мероприятия
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Приватное или нет
	IsPrivate bool `protobuf:"varint,3,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	// Длительность
	DurationMinutes int32 `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	// Дата время начала мероприятия
	StartsAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	// Название локации
	LocationName string `protobuf:"bytes,6,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	// Максимальное количество участников
	MaxParticipants int32 `protobuf:"varint,7,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	// Опционально: координаты мероприятия
	LocationCoords *string `protobuf:"bytes,8,opt,name=location_coords,json=locationCoords,proto3,oneof" json:"location_coords,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_proto_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *CreateEventRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *CreateEventRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *CreateEventRequest) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *CreateEventRequest) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *CreateEventRequest) GetLocationCoords() string {
	if x != nil && x.LocationCoords != nil {
		return *x.LocationCoords
	}
	return ""
}

// Ответ на создание мероприятия - его id
type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_proto_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{4}
}

func (x *CreateEventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Запрос на получения списка мероприятий пользователя
type ListUserEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserEventsRequest) Reset() {
	*x = ListUserEventsRequest{}
	mi := &file_proto_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserEventsRequest) ProtoMessage() {}

func (x *ListUserEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserEventsRequest.ProtoReflect.Descriptor instead.
func (*ListUserEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{5}
}

// Ответ на получение списка мероприятий пользователя
type ListUserEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список ивентов
	Events        []*EventInfo `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserEventsResponse) Reset() {
	*x = ListUserEventsResponse{}
	mi := &file_proto_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserEventsResponse) ProtoMessage() {}

func (x *ListUserEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserEventsResponse.ProtoReflect.Descriptor instead.
func (*ListUserEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserEventsResponse) GetEvents() []*EventInfo {
	if x != nil {
		return x.Events
	}
	return nil
}

// Запрос на получение информации об мероприятии
type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_proto_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответ на получение информации о мероприятии
type GetEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Само мероприятие
	Event         *EventInfo `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_proto_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventResponse) GetEvent() *EventInfo {
	if x != nil {
		return x.Event
	}
	return nil
}

// Запрос на обновление данных о мероприятии
type UpdateEventRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Опционально: название мероприятия
	Title *string `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// Опционально: описание мероприятия
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Опционально: дата начала мероприятия
	StartsAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=starts_at,json=startsAt,proto3,oneof" json:"starts_at,omitempty"`
	// Опционально: название локации
	LocationName *string `protobuf:"bytes,5,opt,name=location_name,json=locationName,proto3,oneof" json:"location_name,omitempty"`
	// Опционально: координаты локации
	LocationCoords *string `protobuf:"bytes,6,opt,name=location_coords,json=locationCoords,proto3,oneof" json:"location_coords,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_proto_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *UpdateEventRequest) GetLocationName() string {
	if x != nil && x.LocationName != nil {
		return *x.LocationName
	}
	return ""
}

func (x *UpdateEventRequest) GetLocationCoords() string {
	if x != nil && x.LocationCoords != nil {
		return *x.LocationCoords
	}
	return ""
}

// Ответ на обновление данных о мероприятии - его обновлённые данные
type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *EventInfo             `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_proto_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateEventResponse) GetEvent() *EventInfo {
	if x != nil {
		return x.Event
	}
	return nil
}

// Запрос на получение списка мероприятий (с поддержкой поиска и фильтрации)
type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Поисковый запрос (искать по title и description)
	Title       *string `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Фильтр по дате: показать ивенты, которые начнутся ПОСЛЕ этого времени
	StartsAfter *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=starts_after,json=startsAfter,proto3,oneof" json:"starts_after,omitempty"`
	// Фильтр по дате: показать ивенты, которые начнутся ДО этого времени
	StartsBefore *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=starts_before,json=startsBefore,proto3,oneof" json:"starts_before,omitempty"`
	// Фильтр по локации (точное совпадение или подстрока)
	LocationName  *string `protobuf:"bytes,5,opt,name=location_name,json=locationName,proto3,oneof" json:"location_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_proto_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{11}
}

func (x *ListEventsRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ListEventsRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ListEventsRequest) GetStartsAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAfter
	}
	return nil
}

func (x *ListEventsRequest) GetStartsBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsBefore
	}
	return nil
}

func (x *ListEventsRequest) GetLocationName() string {
	if x != nil && x.LocationName != nil {
		return *x.LocationName
	}
	return ""
}

// Ответ на запрос получения списка мероприятий
type ListEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список всех мероприятий
	Events        []*EventInfo `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_proto_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{12}
}

func (x *ListEventsResponse) GetEvents() []*EventInfo {
	if x != nil {
		return x.Events
	}
	return nil
}

// Запрос на присоединение к мероприятию
type JoinEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// код для ссылки-приглашения на мероприятие
	EventCode     string `protobuf:"bytes,1,opt,name=event_code,json=eventCode,proto3" json:"event_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinEventRequest) Reset() {
	*x = JoinEventRequest{}
	mi := &file_proto_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinEventRequest) ProtoMessage() {}

func (x *JoinEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinEventRequest.ProtoReflect.Descriptor instead.
func (*JoinEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{13}
}

func (x *JoinEventRequest) GetEventCode() string {
	if x != nil {
		return x.EventCode
	}
	return ""
}

// Ответ на запрос присоединения к мероприятию
type JoinEventResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Успешно/не успешно
	Success       bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinEventResponse) Reset() {
	*x = JoinEventResponse{}
	mi := &file_proto_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinEventResponse) ProtoMessage() {}

func (x *JoinEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinEventResponse.ProtoReflect.Descriptor instead.
func (*JoinEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{14}
}

func (x *JoinEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *JoinEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на выход из мероприятия конкретного пользователя
type LeaveEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // user_id передавать через контекст
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveEventRequest) Reset() {
	*x = LeaveEventRequest{}
	mi := &file_proto_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveEventRequest) ProtoMessage() {}

func (x *LeaveEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveEventRequest.ProtoReflect.Descriptor instead.
func (*LeaveEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{15}
}

func (x *LeaveEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// Ответ на запрос выхода из мероприятия
type LeaveEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Успешно/ не успешно
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveEventResponse) Reset() {
	*x = LeaveEventResponse{}
	mi := &file_proto_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveEventResponse) ProtoMessage() {}

func (x *LeaveEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveEventResponse.ProtoReflect.Descriptor instead.
func (*LeaveEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{16}
}

func (x *LeaveEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Удалить участника из мероприятия
type RemoveParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantRequest) Reset() {
	*x = RemoveParticipantRequest{}
	mi := &file_proto_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantRequest) ProtoMessage() {}

func (x *RemoveParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantRequest.ProtoReflect.Descriptor instead.
func (*RemoveParticipantRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveParticipantRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RemoveParticipantRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

// Ответ на запрос по удалению из мероприятия
type RemoveParticipantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Успешно/ не успешно
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantResponse) Reset() {
	*x = RemoveParticipantResponse{}
	mi := &file_proto_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantResponse) ProtoMessage() {}

func (x *RemoveParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantResponse.ProtoReflect.Descriptor instead.
func (*RemoveParticipantResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveParticipantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на получение списка всех участников мероприятия
type GetEventParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventParticipantsRequest) Reset() {
	*x = GetEventParticipantsRequest{}
	mi := &file_proto_event_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventParticipantsRequest) ProtoMessage() {}

func (x *GetEventParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventParticipantsRequest.ProtoReflect.Descriptor instead.
func (*GetEventParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{19}
}

func (x *GetEventParticipantsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// Ответ на запрос получения списка всех участников мероприятия
type GetEventParticipantsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список всех участников
	Participants  []*ParticipantInfo `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventParticipantsResponse) Reset() {
	*x = GetEventParticipantsResponse{}
	mi := &file_proto_event_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventParticipantsResponse) ProtoMessage() {}

func (x *GetEventParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventParticipantsResponse.ProtoReflect.Descriptor instead.
func (*GetEventParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{20}
}

func (x *GetEventParticipantsResponse) GetParticipants() []*ParticipantInfo {
	if x != nil {
		return x.Participants
	}
	return nil
}

// Запрос на добавление элемента в чеклист
type AddChecklistItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddChecklistItemRequest) Reset() {
	*x = AddChecklistItemRequest{}
	mi := &file_proto_event_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChecklistItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChecklistItemRequest) ProtoMessage() {}

func (x *AddChecklistItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChecklistItemRequest.ProtoReflect.Descriptor instead.
func (*AddChecklistItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{21}
}

func (x *AddChecklistItemRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AddChecklistItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddChecklistItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddChecklistItemRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// Ответ на запрос добавления элемента в чеклист
type AddChecklistItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddChecklistItemResponse) Reset() {
	*x = AddChecklistItemResponse{}
	mi := &file_proto_event_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChecklistItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChecklistItemResponse) ProtoMessage() {}

func (x *AddChecklistItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChecklistItemResponse.ProtoReflect.Descriptor instead.
func (*AddChecklistItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{22}
}

func (x *AddChecklistItemResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

// Запрос на удаление предмета из чеклиста
type RemoveChecklistItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveChecklistItemRequest) Reset() {
	*x = RemoveChecklistItemRequest{}
	mi := &file_proto_event_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveChecklistItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChecklistItemRequest) ProtoMessage() {}

func (x *RemoveChecklistItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChecklistItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveChecklistItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveChecklistItemRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RemoveChecklistItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

// Ответ на запрос удаления предмета из чеклиста
type RemoveChecklistItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveChecklistItemResponse) Reset() {
	*x = RemoveChecklistItemResponse{}
	mi := &file_proto_event_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveChecklistItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChecklistItemResponse) ProtoMessage() {}

func (x *RemoveChecklistItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChecklistItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveChecklistItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveChecklistItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на изменения статуса покупки предмета из чеклиста
type MarkItemPurchasedRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ItemId  string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// id ответственного (если нужно его добавить/изменить)
	BuyerId *string `protobuf:"bytes,3,opt,name=buyer_id,json=buyerId,proto3,oneof" json:"buyer_id,omitempty"`
	// куплено/ не куплено
	IsPurchased   *bool `protobuf:"varint,4,opt,name=is_purchased,json=isPurchased,proto3,oneof" json:"is_purchased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkItemPurchasedRequest) Reset() {
	*x = MarkItemPurchasedRequest{}
	mi := &file_proto_event_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkItemPurchasedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkItemPurchasedRequest) ProtoMessage() {}

func (x *MarkItemPurchasedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkItemPurchasedRequest.ProtoReflect.Descriptor instead.
func (*MarkItemPurchasedRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{25}
}

func (x *MarkItemPurchasedRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MarkItemPurchasedRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *MarkItemPurchasedRequest) GetBuyerId() string {
	if x != nil && x.BuyerId != nil {
		return *x.BuyerId
	}
	return ""
}

func (x *MarkItemPurchasedRequest) GetIsPurchased() bool {
	if x != nil && x.IsPurchased != nil {
		return *x.IsPurchased
	}
	return false
}

// Ответ на запрос изменения статуса покупки предмета из чеклиста
type MarkItemPurchasedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// успешно / не успешно
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkItemPurchasedResponse) Reset() {
	*x = MarkItemPurchasedResponse{}
	mi := &file_proto_event_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkItemPurchasedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkItemPurchasedResponse) ProtoMessage() {}

func (x *MarkItemPurchasedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkItemPurchasedResponse.ProtoReflect.Descriptor instead.
func (*MarkItemPurchasedResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{26}
}

func (x *MarkItemPurchasedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на получение чеклиста мероприятия
type GetEventChecklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventChecklistRequest) Reset() {
	*x = GetEventChecklistRequest{}
	mi := &file_proto_event_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventChecklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventChecklistRequest) ProtoMessage() {}

func (x *GetEventChecklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventChecklistRequest.ProtoReflect.Descriptor instead.
func (*GetEventChecklistRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{27}
}

func (x *GetEventChecklistRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// Ответ на запрос получения чеклиста мероприятия
type GetEventChecklistResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список предметов в чеклисте
	Checklist     []*ChecklistItemInfo `protobuf:"bytes,1,rep,name=checklist,proto3" json:"checklist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventChecklistResponse) Reset() {
	*x = GetEventChecklistResponse{}
	mi := &file_proto_event_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventChecklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventChecklistResponse) ProtoMessage() {}

func (x *GetEventChecklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventChecklistResponse.ProtoReflect.Descriptor instead.
func (*GetEventChecklistResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{28}
}

func (x *GetEventChecklistResponse) GetChecklist() []*ChecklistItemInfo {
	if x != nil {
		return x.Checklist
	}
	return nil
}

// Запрос на отмену мероприятия
type CancelEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEventRequest) Reset() {
	*x = CancelEventRequest{}
	mi := &file_proto_event_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEventRequest) ProtoMessage() {}

func (x *CancelEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEventRequest.ProtoReflect.Descriptor instead.
func (*CancelEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{29}
}

func (x *CancelEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// Ответ на запрос по отмене мероприятия
type CancelEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Успешно/ не успешно
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEventResponse) Reset() {
	*x = CancelEventResponse{}
	mi := &file_proto_event_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEventResponse) ProtoMessage() {}

func (x *CancelEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEventResponse.ProtoReflect.Descriptor instead.
func (*CancelEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{30}
}

func (x *CancelEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на создание ссылки-приглашения
type CreateInviteLinkRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Тип приглашения (single/multi/unlimited)
	InviteType string `protobuf:"bytes,2,opt,name=invite_type,json=inviteType,proto3" json:"invite_type,omitempty"`
	// До какого момента действует ссылка
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteLinkRequest) Reset() {
	*x = CreateInviteLinkRequest{}
	mi := &file_proto_event_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteLinkRequest) ProtoMessage() {}

func (x *CreateInviteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{31}
}

func (x *CreateInviteLinkRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateInviteLinkRequest) GetInviteType() string {
	if x != nil {
		return x.InviteType
	}
	return ""
}

func (x *CreateInviteLinkRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Ответ на запрос создания ссылки приглашения
type CreateInviteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventCode     string                 `protobuf:"bytes,1,opt,name=event_code,json=eventCode,proto3" json:"event_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteLinkResponse) Reset() {
	*x = CreateInviteLinkResponse{}
	mi := &file_proto_event_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteLinkResponse) ProtoMessage() {}

func (x *CreateInviteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateInviteLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{32}
}

func (x *CreateInviteLinkResponse) GetEventCode() string {
	if x != nil {
		return x.EventCode
	}
	return ""
}

var File_proto_event_proto protoreflect.FileDescriptor

const file_proto_event_proto_rawDesc = "" +
	"\n" +
	"\x11proto/event.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x01\n" +
	"\tEventInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\tstarts_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"is_private\x18\a \x01(\bR\tisPrivate\"d\n" +
	"\x0fParticipantInfo\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xcf\x01\n" +
	"\x11ChecklistItemInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x1e\n" +
	"\bbuyer_id\x18\x05 \x01(\tH\x00R\abuyerId\x88\x01\x01\x12&\n" +
	"\fis_purchased\x18\x06 \x01(\bH\x01R\visPurchased\x88\x01\x01B\v\n" +
	"\t_buyer_idB\x0f\n" +
	"\r_is_purchased\"\xe1\x02\n" +
	"\x12CreateEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"is_private\x18\x03 \x01(\bR\tisPrivate\x12)\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05R\x0fdurationMinutes\x127\n" +
	"\tstarts_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x12#\n" +
	"\rlocation_name\x18\x06 \x01(\tR\flocationName\x12)\n" +
	"\x10max_participants\x18\a \x01(\x05R\x0fmaxParticipants\x12,\n" +
	"\x0flocation_coords\x18\b \x01(\tH\x00R\x0elocationCoords\x88\x01\x01B\x12\n" +
	"\x10_location_coords\"%\n" +
	"\x13CreateEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15ListUserEventsRequest\"B\n" +
	"\x16ListUserEventsResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.event.EventInfoR\x06events\"!\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x10GetEventResponse\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x10.event.EventInfoR\x05event\"\xd5\x02\n" +
	"\x12UpdateEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12<\n" +
	"\tstarts_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\bstartsAt\x88\x01\x01\x12(\n" +
	"\rlocation_name\x18\x05 \x01(\tH\x03R\flocationName\x88\x01\x01\x12,\n" +
	"\x0flocation_coords\x18\x06 \x01(\tH\x04R\x0elocationCoords\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_starts_atB\x10\n" +
	"\x0e_location_nameB\x12\n" +
	"\x10_location_coords\"=\n" +
	"\x13UpdateEventResponse\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x10.event.EventInfoR\x05event\"\xd8\x02\n" +
	"\x11ListEventsRequest\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12B\n" +
	"\fstarts_after\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vstartsAfter\x88\x01\x01\x12D\n" +
	"\rstarts_before\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\fstartsBefore\x88\x01\x01\x12(\n" +
	"\rlocation_name\x18\x05 \x01(\tH\x04R\flocationName\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_starts_afterB\x10\n" +
	"\x0e_starts_beforeB\x10\n" +
	"\x0e_location_name\">\n" +
	"\x12ListEventsResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.event.EventInfoR\x06events\"1\n" +
	"\x10JoinEventRequest\x12\x1d\n" +
	"\n" +
	"event_code\x18\x01 \x01(\tR\teventCode\"H\n" +
	"\x11JoinEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\".\n" +
	"\x11LeaveEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\".\n" +
	"\x12LeaveEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\x18RemoveParticipantRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\"5\n" +
	"\x19RemoveParticipantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x1bGetEventParticipantsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"Z\n" +
	"\x1cGetEventParticipantsResponse\x12:\n" +
	"\fparticipants\x18\x01 \x03(\v2\x16.event.ParticipantInfoR\fparticipants\"z\n" +
	"\x17AddChecklistItemRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\"3\n" +
	"\x18AddChecklistItemResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"P\n" +
	"\x1aRemoveChecklistItemRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\"7\n" +
	"\x1bRemoveChecklistItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb4\x01\n" +
	"\x18MarkItemPurchasedRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1e\n" +
	"\bbuyer_id\x18\x03 \x01(\tH\x00R\abuyerId\x88\x01\x01\x12&\n" +
	"\fis_purchased\x18\x04 \x01(\bH\x01R\visPurchased\x88\x01\x01B\v\n" +
	"\t_buyer_idB\x0f\n" +
	"\r_is_purchased\"5\n" +
	"\x19MarkItemPurchasedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x18GetEventChecklistRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"S\n" +
	"\x19GetEventChecklistResponse\x126\n" +
	"\tchecklist\x18\x01 \x03(\v2\x18.event.ChecklistItemInfoR\tchecklist\"/\n" +
	"\x12CancelEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"/\n" +
	"\x13CancelEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x90\x01\n" +
	"\x17CreateInviteLinkRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vinvite_type\x18\x02 \x01(\tR\n" +
	"inviteType\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"9\n" +
	"\x18CreateInviteLinkResponse\x12\x1d\n" +
	"\n" +
	"event_code\x18\x01 \x01(\tR\teventCode2\xa3\t\n" +
	"\fEventService\x12D\n" +
	"\vCreateEvent\x12\x19.event.CreateEventRequest\x1a\x1a.event.CreateEventResponse\x12M\n" +
	"\x0eListUserEvents\x12\x1c.event.ListUserEventsRequest\x1a\x1d.event.ListUserEventsResponse\x12A\n" +
	"\n" +
	"ListEvents\x12\x18.event.ListEventsRequest\x1a\x19.event.ListEventsResponse\x12;\n" +
	"\bGetEvent\x12\x16.event.GetEventRequest\x1a\x17.event.GetEventResponse\x12D\n" +
	"\vUpdateEvent\x12\x19.event.UpdateEventRequest\x1a\x1a.event.UpdateEventResponse\x12>\n" +
	"\tJoinEvent\x12\x17.event.JoinEventRequest\x1a\x18.event.JoinEventResponse\x12A\n" +
	"\n" +
	"LeaveEvent\x12\x18.event.LeaveEventRequest\x1a\x19.event.LeaveEventResponse\x12V\n" +
	"\x11RemoveParticipant\x12\x1f.event.RemoveParticipantRequest\x1a .event.RemoveParticipantResponse\x12_\n" +
	"\x14GetEventParticipants\x12\".event.GetEventParticipantsRequest\x1a#.event.GetEventParticipantsResponse\x12S\n" +
	"\x10AddChecklistItem\x12\x1e.event.AddChecklistItemRequest\x1a\x1f.event.AddChecklistItemResponse\x12\\\n" +
	"\x13RemoveChecklistItem\x12!.event.RemoveChecklistItemRequest\x1a\".event.RemoveChecklistItemResponse\x12V\n" +
	"\x11MarkItemPurchased\x12\x1f.event.MarkItemPurchasedRequest\x1a .event.MarkItemPurchasedResponse\x12V\n" +
	"\x11GetEventChecklist\x12\x1f.event.GetEventChecklistRequest\x1a .event.GetEventChecklistResponse\x12D\n" +
	"\vCancelEvent\x12\x19.event.CancelEventRequest\x1a\x1a.event.CancelEventResponse\x12S\n" +
	"\x10CreateInviteLink\x12\x1e.event.CreateInviteLinkRequest\x1a\x1f.event.CreateInviteLinkResponseB\fZ\n" +
	"pkg/api/v1b\x06proto3"

var (
	file_proto_event_proto_rawDescOnce sync.Once
	file_proto_event_proto_rawDescData []byte
)

func file_proto_event_proto_rawDescGZIP() []byte {
	file_proto_event_proto_rawDescOnce.Do(func() {
		file_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_event_proto_rawDesc), len(file_proto_event_proto_rawDesc)))
	})
	return file_proto_event_proto_rawDescData
}

var file_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_event_proto_goTypes = []any{
	(*EventInfo)(nil),                    // 0: event.EventInfo
	(*ParticipantInfo)(nil),              // 1: event.ParticipantInfo
	(*ChecklistItemInfo)(nil),            // 2: event.ChecklistItemInfo
	(*CreateEventRequest)(nil),           // 3: event.CreateEventRequest
	(*CreateEventResponse)(nil),          // 4: event.CreateEventResponse
	(*ListUserEventsRequest)(nil),        // 5: event.ListUserEventsRequest
	(*ListUserEventsResponse)(nil),       // 6: event.ListUserEventsResponse
	(*GetEventRequest)(nil),              // 7: event.GetEventRequest
	(*GetEventResponse)(nil),             // 8: event.GetEventResponse
	(*UpdateEventRequest)(nil),           // 9: event.UpdateEventRequest
	(*UpdateEventResponse)(nil),          // 10: event.UpdateEventResponse
	(*ListEventsRequest)(nil),            // 11: event.ListEventsRequest
	(*ListEventsResponse)(nil),           // 12: event.ListEventsResponse
	(*JoinEventRequest)(nil),             // 13: event.JoinEventRequest
	(*JoinEventResponse)(nil),            // 14: event.JoinEventResponse
	(*LeaveEventRequest)(nil),            // 15: event.LeaveEventRequest
	(*LeaveEventResponse)(nil),           // 16: event.LeaveEventResponse
	(*RemoveParticipantRequest)(nil),     // 17: event.RemoveParticipantRequest
	(*RemoveParticipantResponse)(nil),    // 18: event.RemoveParticipantResponse
	(*GetEventParticipantsRequest)(nil),  // 19: event.GetEventParticipantsRequest
	(*GetEventParticipantsResponse)(nil), // 20: event.GetEventParticipantsResponse
	(*AddChecklistItemRequest)(nil),      // 21: event.AddChecklistItemRequest
	(*AddChecklistItemResponse)(nil),     // 22: event.AddChecklistItemResponse
	(*RemoveChecklistItemRequest)(nil),   // 23: event.RemoveChecklistItemRequest
	(*RemoveChecklistItemResponse)(nil),  // 24: event.RemoveChecklistItemResponse
	(*MarkItemPurchasedRequest)(nil),     // 25: event.MarkItemPurchasedRequest
	(*MarkItemPurchasedResponse)(nil),    // 26: event.MarkItemPurchasedResponse
	(*GetEventChecklistRequest)(nil),     // 27: event.GetEventChecklistRequest
	(*GetEventChecklistResponse)(nil),    // 28: event.GetEventChecklistResponse
	(*CancelEventRequest)(nil),           // 29: event.CancelEventRequest
	(*CancelEventResponse)(nil),          // 30: event.CancelEventResponse
	(*CreateInviteLinkRequest)(nil),      // 31: event.CreateInviteLinkRequest
	(*CreateInviteLinkResponse)(nil),     // 32: event.CreateInviteLinkResponse
	(*timestamppb.Timestamp)(nil),        // 33: google.protobuf.Timestamp
}
var file_proto_event_proto_depIdxs = []int32{
	33, // 0: event.EventInfo.starts_at:type_name -> google.protobuf.Timestamp
	33, // 1: event.CreateEventRequest.starts_at:type_name -> google.protobuf.Timestamp
	0,  // 2: event.ListUserEventsResponse.events:type_name -> event.EventInfo
	0,  // 3: event.GetEventResponse.event:type_name -> event.EventInfo
	33, // 4: event.UpdateEventRequest.starts_at:type_name -> google.protobuf.Timestamp
	0,  // 5: event.UpdateEventResponse.event:type_name -> event.EventInfo
	33, // 6: event.ListEventsRequest.starts_after:type_name -> google.protobuf.Timestamp
	33, // 7: event.ListEventsRequest.starts_before:type_name -> google.protobuf.Timestamp
	0,  // 8: event.ListEventsResponse.events:type_name -> event.EventInfo
	1,  // 9: event.GetEventParticipantsResponse.participants:type_name -> event.ParticipantInfo
	2,  // 10: event.GetEventChecklistResponse.checklist:type_name -> event.ChecklistItemInfo
	33, // 11: event.CreateInviteLinkRequest.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 12: event.EventService.CreateEvent:input_type -> event.CreateEventRequest
	5,  // 13: event.EventService.ListUserEvents:input_type -> event.ListUserEventsRequest
	11, // 14: event.EventService.ListEvents:input_type -> event.ListEventsRequest
	7,  // 15: event.EventService.GetEvent:input_type -> event.GetEventRequest
	9,  // 16: event.EventService.UpdateEvent:input_type -> event.UpdateEventRequest
	13, // 17: event.EventService.JoinEvent:input_type -> event.JoinEventRequest
	15, // 18: event.EventService.LeaveEvent:input_type -> event.LeaveEventRequest
	17, // 19: event.EventService.RemoveParticipant:input_type -> event.RemoveParticipantRequest
	19, // 20: event.EventService.GetEventParticipants:input_type -> event.GetEventParticipantsRequest
	21, // 21: event.EventService.AddChecklistItem:input_type -> event.AddChecklistItemRequest
	23, // 22: event.EventService.RemoveChecklistItem:input_type -> event.RemoveChecklistItemRequest
	25, // 23: event.EventService.MarkItemPurchased:input_type -> event.MarkItemPurchasedRequest
	27, // 24: event.EventService.GetEventChecklist:input_type -> event.GetEventChecklistRequest
	29, // 25: event.EventService.CancelEvent:input_type -> event.CancelEventRequest
	31, // 26: event.EventService.CreateInviteLink:input_type -> event.CreateInviteLinkRequest
	4,  // 27: event.EventService.CreateEvent:output_type -> event.CreateEventResponse
	6,  // 28: event.EventService.ListUserEvents:output_type -> event.ListUserEventsResponse
	12, // 29: event.EventService.ListEvents:output_type -> event.ListEventsResponse
	8,  // 30: event.EventService.GetEvent:output_type -> event.GetEventResponse
	10, // 31: event.EventService.UpdateEvent:output_type -> event.UpdateEventResponse
	14, // 32: event.EventService.JoinEvent:output_type -> event.JoinEventResponse
	16, // 33: event.EventService.LeaveEvent:output_type -> event.LeaveEventResponse
	18, // 34: event.EventService.RemoveParticipant:output_type -> event.RemoveParticipantResponse
	20, // 35: event.EventService.GetEventParticipants:output_type -> event.GetEventParticipantsResponse
	22, // 36: event.EventService.AddChecklistItem:output_type -> event.AddChecklistItemResponse
	24, // 37: event.EventService.RemoveChecklistItem:output_type -> event.RemoveChecklistItemResponse
	26, // 38: event.EventService.MarkItemPurchased:output_type -> event.MarkItemPurchasedResponse
	28, // 39: event.EventService.GetEventChecklist:output_type -> event.GetEventChecklistResponse
	30, // 40: event.EventService.CancelEvent:output_type -> event.CancelEventResponse
	32, // 41: event.EventService.CreateInviteLink:output_type -> event.CreateInviteLinkResponse
	27, // [27:42] is the sub-list for method output_type
	12, // [12:27] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_event_proto_init() }
func file_proto_event_proto_init() {
	if File_proto_event_proto != nil {
		return
	}
	file_proto_event_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_event_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_event_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_event_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_event_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_event_proto_rawDesc), len(file_proto_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_event_proto_goTypes,
		DependencyIndexes: file_proto_event_proto_depIdxs,
		MessageInfos:      file_proto_event_proto_msgTypes,
	}.Build()
	File_proto_event_proto = out.File
	file_proto_event_proto_goTypes = nil
	file_proto_event_proto_depIdxs = nil
}
